//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tickets
    {
        public tb_tickets()
        {
            this.tbl_gameplay = new HashSet<tbl_gameplay>();
            this.tbl_games = new HashSet<tbl_games>();
            this.tbl_winner = new HashSet<tbl_winner>();
        }
    
        public int ticketId { get; set; }
        public Nullable<int> R1C1 { get; set; }
        public Nullable<int> R1C2 { get; set; }
        public Nullable<int> R1C3 { get; set; }
        public Nullable<int> R1C4 { get; set; }
        public Nullable<int> R1C5 { get; set; }
        public Nullable<int> R1C6 { get; set; }
        public Nullable<int> R1C7 { get; set; }
        public Nullable<int> R1C8 { get; set; }
        public Nullable<int> R1C9 { get; set; }
        public Nullable<int> R2C1 { get; set; }
        public Nullable<int> R2C2 { get; set; }
        public Nullable<int> R2C3 { get; set; }
        public Nullable<int> R2C4 { get; set; }
        public Nullable<int> R2C5 { get; set; }
        public Nullable<int> R2C6 { get; set; }
        public Nullable<int> R2C7 { get; set; }
        public Nullable<int> R2C8 { get; set; }
        public Nullable<int> R2C9 { get; set; }

        public Nullable<int> R3C1 { get; set; }
        public Nullable<int> R3C2 { get; set; }
        public Nullable<int> R3C3 { get; set; }
        public Nullable<int> R3C4 { get; set; }
        public Nullable<int> R3C5 { get; set; }
        public Nullable<int> R3C6 { get; set; }
        public Nullable<int> R3C7 { get; set; }
        public Nullable<int> R3C8 { get; set; }
        public Nullable<int> R3C9 { get; set; }


        public virtual ICollection<tbl_gameplay> tbl_gameplay { get; set; }
        public virtual ICollection<tbl_games> tbl_games { get; set; }
        public virtual ICollection<tbl_winner> tbl_winner { get; set; }
    }
}
