//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customers
    {
        public tbl_customers()
        {
            this.tbl_games = new HashSet<tbl_games>();
        }
    
        public int custId { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string password { get; set; }
        public string paypal_id { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public string facebookLink { get; set; }
        public Nullable<bool> bool_emailstatus { get; set; }
        public Nullable<System.DateTime> dateTImestamp { get; set; }
        public string phoneNum { get; set; }
    
        public virtual ICollection<tbl_games> tbl_games { get; set; }
    }
}
