//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gamemaster
    {
        public tbl_gamemaster()
        {
            this.tbl_gameplay = new HashSet<tbl_gameplay>();
            this.tbl_games = new HashSet<tbl_games>();
            this.tbl_picknumber = new HashSet<tbl_picknumber>();
            this.tbl_winner = new HashSet<tbl_winner>();
        }
    
        public int gameId { get; set; }
        public Nullable<System.DateTime> start_dateTime { get; set; }
        public Nullable<bool> is_completed { get; set; }
    
        public virtual ICollection<tbl_gameplay> tbl_gameplay { get; set; }
        public virtual ICollection<tbl_games> tbl_games { get; set; }
        public virtual ICollection<tbl_picknumber> tbl_picknumber { get; set; }
        public virtual ICollection<tbl_winner> tbl_winner { get; set; }
    }
}
