//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_games
    {
        public int id { get; set; }
        public int gameId { get; set; }
        public int custId { get; set; }
        public int ticketid { get; set; }
        public Nullable<System.DateTime> datetimestamp { get; set; }
    
        public virtual tb_tickets tb_tickets { get; set; }
        public virtual tbl_customers tbl_customers { get; set; }
        public virtual tbl_gamemaster tbl_gamemaster { get; set; }
    }
}
