//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gameplay
    {
        public int id { get; set; }
        public int gameId { get; set; }
        public int ticketId { get; set; }
        public Nullable<int> pick_number { get; set; }
        public string rowcellnumber { get; set; }
    
        public virtual tb_tickets tb_tickets { get; set; }
        public virtual tbl_gamemaster tbl_gamemaster { get; set; }
    }
}
